language: cpp
dist: trusty
sudo: required

notifications:
  email: false

git:
  submodules: false
  depth: 3

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['python-pip', 'python-yaml']
      install:
        - pip install --user cpp-coveralls
      script:
          - mkdir build && cd build
          - cmake -DGCOV_SUPPORT=On ..
          - cmake --build .
          - cd ../
          - ./build/hoatest
      after_success:
        - coveralls -e build/CMakeFiles/feature_tests.cxx -e build/CMakeFiles/feature_tests.c -e build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.cpp -e build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.c -e build/CMakeFiles/3.2.2/CompilerIdCXX/CMakeCXXCompilerId.cpp -e build/CMakeFiles/3.2.2/CompilerIdC/CMakeCCompilerId.c -e Tests --gcov-options '\-lp'
      env:
        - Coveralls

    - os: linux
      compiler: gcc

    - os: linux
      compiler: clang
      env:
        - Libs and Tests

    - os: osx
      compiler: gcc
      env:
        - Libs and Tests

    - os: osx
      compiler: clang
      env:
        - Libs and Tests

script:
  - mkdir build && cd build
  - cmake ..
  - cmake --build .
  - cd ../
  - ./build/hoatest
