language: c
dist: trusty
sudo: required

notifications:
  email: false

git:
  submodules: true
  depth: 3

matrix:
  include:
    - os: linux
      compiler: gcc
      addons:
        apt:
          packages: ['python-pip', 'python-yaml']
      install:
        - pip install --user cpp-coveralls
      script:
          - mkdir build && cd build
          - cmake -DGCOV_SUPPORT=On ..
          - cmake --build .
          - cd ../
          - ./build/test

      after_success:
        - coveralls -e build/CMakeFiles/feature_tests.cxx -e build/CMakeFiles/feature_tests.c -e build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.cpp -e build/CMakeFiles/CompilerIdCXX/CMakeCXXCompilerId.c -e build/CMakeFiles/3.2.2/CompilerIdCXX/CMakeCXXCompilerId.cpp -e build/CMakeFiles/3.2.2/CompilerIdC/CMakeCCompilerId.c -e test -e pd -e thread --gcov-options '\-lp'
      env:
        - Coveralls

    - os: linux
      compiler: gcc
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
        - cd ../
        - ./build/test
      env:
        - Libs and Tests

    - os: linux
      compiler: clang
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
        - cd ../
        - ./build/test
      env:
        - Libs and Tests

    - os: osx
      compiler: gcc
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
        - cd ../
        - ./build/test
      env:
        - Libs and Tests

    - os: osx
      compiler: clang
      script:
        - mkdir build && cd build
        - cmake ..
        - cmake --build .
        - cd ../
        - ./build/test
      env:
        - Libs and Tests
